---
- name: install apache2
  apt: name=apache2 update_cache=yes state=latest

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart-apache

- name: install PHP module for Apache
  apt: name=libapache2-mod-php5 state=present
  notify:
    - restart-apache

- name: copy simpleweb template to /var/www/html/ folder
  import_tasks: create-index.yml
